// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: S2CLoginMsg.proto

package org.game.protobuf.s2c;

public final class S2CLoginMsg {
  private S2CLoginMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code org.game.protobuf.s2c.LogoutType}
   */
  public enum LogoutType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>COMMON = 0;</code>
     */
    COMMON(0),
    /**
     * <code>KICK_OUT = 1;</code>
     */
    KICK_OUT(1),
    /**
     * <code>OTHER_PLACES_ON = 2;</code>
     */
    OTHER_PLACES_ON(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>COMMON = 0;</code>
     */
    public static final int COMMON_VALUE = 0;
    /**
     * <code>KICK_OUT = 1;</code>
     */
    public static final int KICK_OUT_VALUE = 1;
    /**
     * <code>OTHER_PLACES_ON = 2;</code>
     */
    public static final int OTHER_PLACES_ON_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static LogoutType valueOf(int value) {
      return forNumber(value);
    }

    public static LogoutType forNumber(int value) {
      switch (value) {
        case 0: return COMMON;
        case 1: return KICK_OUT;
        case 2: return OTHER_PLACES_ON;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<LogoutType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        LogoutType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<LogoutType>() {
            public LogoutType findValueByNumber(int number) {
              return LogoutType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.game.protobuf.s2c.S2CLoginMsg.getDescriptor().getEnumTypes().get(0);
    }

    private static final LogoutType[] VALUES = values();

    public static LogoutType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private LogoutType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:org.game.protobuf.s2c.LogoutType)
  }

  public interface S2CLoginMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.game.protobuf.s2c.S2CLoginMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *服务器时间
     * </pre>
     *
     * <code>optional int32 serverTime = 1;</code>
     */
    int getServerTime();
  }
  /**
   * <pre>
   *登陆反馈
   * code = 257
   * </pre>
   *
   * Protobuf type {@code org.game.protobuf.s2c.S2CLoginMessage}
   */
  public  static final class S2CLoginMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.game.protobuf.s2c.S2CLoginMessage)
      S2CLoginMessageOrBuilder {
    // Use S2CLoginMessage.newBuilder() to construct.
    private S2CLoginMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private S2CLoginMessage() {
      serverTime_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private S2CLoginMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              serverTime_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.game.protobuf.s2c.S2CLoginMsg.internal_static_org_game_protobuf_s2c_S2CLoginMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.game.protobuf.s2c.S2CLoginMsg.internal_static_org_game_protobuf_s2c_S2CLoginMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.game.protobuf.s2c.S2CLoginMsg.S2CLoginMessage.class, org.game.protobuf.s2c.S2CLoginMsg.S2CLoginMessage.Builder.class);
    }

    /**
     * Protobuf enum {@code org.game.protobuf.s2c.S2CLoginMessage.MsgID}
     */
    public enum MsgID
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ENUN_TYPE_UNSPECIFIED = 0;</code>
       */
      ENUN_TYPE_UNSPECIFIED(0),
      /**
       * <code>eMsgID = 257;</code>
       */
      eMsgID(257),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>ENUN_TYPE_UNSPECIFIED = 0;</code>
       */
      public static final int ENUN_TYPE_UNSPECIFIED_VALUE = 0;
      /**
       * <code>eMsgID = 257;</code>
       */
      public static final int eMsgID_VALUE = 257;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MsgID valueOf(int value) {
        return forNumber(value);
      }

      public static MsgID forNumber(int value) {
        switch (value) {
          case 0: return ENUN_TYPE_UNSPECIFIED;
          case 257: return eMsgID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MsgID> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgID>() {
              public MsgID findValueByNumber(int number) {
                return MsgID.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.game.protobuf.s2c.S2CLoginMsg.S2CLoginMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final MsgID[] VALUES = values();

      public static MsgID valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MsgID(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:org.game.protobuf.s2c.S2CLoginMessage.MsgID)
    }

    public static final int SERVERTIME_FIELD_NUMBER = 1;
    private int serverTime_;
    /**
     * <pre>
     *服务器时间
     * </pre>
     *
     * <code>optional int32 serverTime = 1;</code>
     */
    public int getServerTime() {
      return serverTime_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (serverTime_ != 0) {
        output.writeInt32(1, serverTime_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (serverTime_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, serverTime_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.game.protobuf.s2c.S2CLoginMsg.S2CLoginMessage)) {
        return super.equals(obj);
      }
      org.game.protobuf.s2c.S2CLoginMsg.S2CLoginMessage other = (org.game.protobuf.s2c.S2CLoginMsg.S2CLoginMessage) obj;

      boolean result = true;
      result = result && (getServerTime()
          == other.getServerTime());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + SERVERTIME_FIELD_NUMBER;
      hash = (53 * hash) + getServerTime();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.game.protobuf.s2c.S2CLoginMsg.S2CLoginMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.protobuf.s2c.S2CLoginMsg.S2CLoginMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.protobuf.s2c.S2CLoginMsg.S2CLoginMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.protobuf.s2c.S2CLoginMsg.S2CLoginMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.protobuf.s2c.S2CLoginMsg.S2CLoginMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.game.protobuf.s2c.S2CLoginMsg.S2CLoginMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.game.protobuf.s2c.S2CLoginMsg.S2CLoginMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.game.protobuf.s2c.S2CLoginMsg.S2CLoginMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.game.protobuf.s2c.S2CLoginMsg.S2CLoginMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.game.protobuf.s2c.S2CLoginMsg.S2CLoginMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.game.protobuf.s2c.S2CLoginMsg.S2CLoginMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *登陆反馈
     * code = 257
     * </pre>
     *
     * Protobuf type {@code org.game.protobuf.s2c.S2CLoginMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.game.protobuf.s2c.S2CLoginMessage)
        org.game.protobuf.s2c.S2CLoginMsg.S2CLoginMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.game.protobuf.s2c.S2CLoginMsg.internal_static_org_game_protobuf_s2c_S2CLoginMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.game.protobuf.s2c.S2CLoginMsg.internal_static_org_game_protobuf_s2c_S2CLoginMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.game.protobuf.s2c.S2CLoginMsg.S2CLoginMessage.class, org.game.protobuf.s2c.S2CLoginMsg.S2CLoginMessage.Builder.class);
      }

      // Construct using org.game.protobuf.s2c.S2CLoginMsg.S2CLoginMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        serverTime_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.game.protobuf.s2c.S2CLoginMsg.internal_static_org_game_protobuf_s2c_S2CLoginMessage_descriptor;
      }

      public org.game.protobuf.s2c.S2CLoginMsg.S2CLoginMessage getDefaultInstanceForType() {
        return org.game.protobuf.s2c.S2CLoginMsg.S2CLoginMessage.getDefaultInstance();
      }

      public org.game.protobuf.s2c.S2CLoginMsg.S2CLoginMessage build() {
        org.game.protobuf.s2c.S2CLoginMsg.S2CLoginMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.game.protobuf.s2c.S2CLoginMsg.S2CLoginMessage buildPartial() {
        org.game.protobuf.s2c.S2CLoginMsg.S2CLoginMessage result = new org.game.protobuf.s2c.S2CLoginMsg.S2CLoginMessage(this);
        result.serverTime_ = serverTime_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.game.protobuf.s2c.S2CLoginMsg.S2CLoginMessage) {
          return mergeFrom((org.game.protobuf.s2c.S2CLoginMsg.S2CLoginMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.game.protobuf.s2c.S2CLoginMsg.S2CLoginMessage other) {
        if (other == org.game.protobuf.s2c.S2CLoginMsg.S2CLoginMessage.getDefaultInstance()) return this;
        if (other.getServerTime() != 0) {
          setServerTime(other.getServerTime());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.game.protobuf.s2c.S2CLoginMsg.S2CLoginMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.game.protobuf.s2c.S2CLoginMsg.S2CLoginMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int serverTime_ ;
      /**
       * <pre>
       *服务器时间
       * </pre>
       *
       * <code>optional int32 serverTime = 1;</code>
       */
      public int getServerTime() {
        return serverTime_;
      }
      /**
       * <pre>
       *服务器时间
       * </pre>
       *
       * <code>optional int32 serverTime = 1;</code>
       */
      public Builder setServerTime(int value) {
        
        serverTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *服务器时间
       * </pre>
       *
       * <code>optional int32 serverTime = 1;</code>
       */
      public Builder clearServerTime() {
        
        serverTime_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:org.game.protobuf.s2c.S2CLoginMessage)
    }

    // @@protoc_insertion_point(class_scope:org.game.protobuf.s2c.S2CLoginMessage)
    private static final org.game.protobuf.s2c.S2CLoginMsg.S2CLoginMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.game.protobuf.s2c.S2CLoginMsg.S2CLoginMessage();
    }

    public static org.game.protobuf.s2c.S2CLoginMsg.S2CLoginMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<S2CLoginMessage>
        PARSER = new com.google.protobuf.AbstractParser<S2CLoginMessage>() {
      public S2CLoginMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new S2CLoginMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<S2CLoginMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<S2CLoginMessage> getParserForType() {
      return PARSER;
    }

    public org.game.protobuf.s2c.S2CLoginMsg.S2CLoginMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PongOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.game.protobuf.s2c.Pong)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *服务器时间
     * </pre>
     *
     * <code>optional int32 serverTime = 1;</code>
     */
    int getServerTime();
  }
  /**
   * <pre>
   * 心跳回执
   * code = 202
   * </pre>
   *
   * Protobuf type {@code org.game.protobuf.s2c.Pong}
   */
  public  static final class Pong extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.game.protobuf.s2c.Pong)
      PongOrBuilder {
    // Use Pong.newBuilder() to construct.
    private Pong(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Pong() {
      serverTime_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Pong(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              serverTime_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.game.protobuf.s2c.S2CLoginMsg.internal_static_org_game_protobuf_s2c_Pong_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.game.protobuf.s2c.S2CLoginMsg.internal_static_org_game_protobuf_s2c_Pong_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.game.protobuf.s2c.S2CLoginMsg.Pong.class, org.game.protobuf.s2c.S2CLoginMsg.Pong.Builder.class);
    }

    /**
     * Protobuf enum {@code org.game.protobuf.s2c.Pong.MsgID}
     */
    public enum MsgID
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ENUN_TYPE_UNSPECIFIED = 0;</code>
       */
      ENUN_TYPE_UNSPECIFIED(0),
      /**
       * <code>eMsgID = 202;</code>
       */
      eMsgID(202),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>ENUN_TYPE_UNSPECIFIED = 0;</code>
       */
      public static final int ENUN_TYPE_UNSPECIFIED_VALUE = 0;
      /**
       * <code>eMsgID = 202;</code>
       */
      public static final int eMsgID_VALUE = 202;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MsgID valueOf(int value) {
        return forNumber(value);
      }

      public static MsgID forNumber(int value) {
        switch (value) {
          case 0: return ENUN_TYPE_UNSPECIFIED;
          case 202: return eMsgID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MsgID> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgID>() {
              public MsgID findValueByNumber(int number) {
                return MsgID.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.game.protobuf.s2c.S2CLoginMsg.Pong.getDescriptor().getEnumTypes().get(0);
      }

      private static final MsgID[] VALUES = values();

      public static MsgID valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MsgID(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:org.game.protobuf.s2c.Pong.MsgID)
    }

    public static final int SERVERTIME_FIELD_NUMBER = 1;
    private int serverTime_;
    /**
     * <pre>
     *服务器时间
     * </pre>
     *
     * <code>optional int32 serverTime = 1;</code>
     */
    public int getServerTime() {
      return serverTime_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (serverTime_ != 0) {
        output.writeInt32(1, serverTime_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (serverTime_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, serverTime_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.game.protobuf.s2c.S2CLoginMsg.Pong)) {
        return super.equals(obj);
      }
      org.game.protobuf.s2c.S2CLoginMsg.Pong other = (org.game.protobuf.s2c.S2CLoginMsg.Pong) obj;

      boolean result = true;
      result = result && (getServerTime()
          == other.getServerTime());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + SERVERTIME_FIELD_NUMBER;
      hash = (53 * hash) + getServerTime();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.game.protobuf.s2c.S2CLoginMsg.Pong parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.protobuf.s2c.S2CLoginMsg.Pong parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.protobuf.s2c.S2CLoginMsg.Pong parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.protobuf.s2c.S2CLoginMsg.Pong parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.protobuf.s2c.S2CLoginMsg.Pong parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.game.protobuf.s2c.S2CLoginMsg.Pong parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.game.protobuf.s2c.S2CLoginMsg.Pong parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.game.protobuf.s2c.S2CLoginMsg.Pong parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.game.protobuf.s2c.S2CLoginMsg.Pong parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.game.protobuf.s2c.S2CLoginMsg.Pong parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.game.protobuf.s2c.S2CLoginMsg.Pong prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 心跳回执
     * code = 202
     * </pre>
     *
     * Protobuf type {@code org.game.protobuf.s2c.Pong}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.game.protobuf.s2c.Pong)
        org.game.protobuf.s2c.S2CLoginMsg.PongOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.game.protobuf.s2c.S2CLoginMsg.internal_static_org_game_protobuf_s2c_Pong_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.game.protobuf.s2c.S2CLoginMsg.internal_static_org_game_protobuf_s2c_Pong_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.game.protobuf.s2c.S2CLoginMsg.Pong.class, org.game.protobuf.s2c.S2CLoginMsg.Pong.Builder.class);
      }

      // Construct using org.game.protobuf.s2c.S2CLoginMsg.Pong.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        serverTime_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.game.protobuf.s2c.S2CLoginMsg.internal_static_org_game_protobuf_s2c_Pong_descriptor;
      }

      public org.game.protobuf.s2c.S2CLoginMsg.Pong getDefaultInstanceForType() {
        return org.game.protobuf.s2c.S2CLoginMsg.Pong.getDefaultInstance();
      }

      public org.game.protobuf.s2c.S2CLoginMsg.Pong build() {
        org.game.protobuf.s2c.S2CLoginMsg.Pong result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.game.protobuf.s2c.S2CLoginMsg.Pong buildPartial() {
        org.game.protobuf.s2c.S2CLoginMsg.Pong result = new org.game.protobuf.s2c.S2CLoginMsg.Pong(this);
        result.serverTime_ = serverTime_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.game.protobuf.s2c.S2CLoginMsg.Pong) {
          return mergeFrom((org.game.protobuf.s2c.S2CLoginMsg.Pong)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.game.protobuf.s2c.S2CLoginMsg.Pong other) {
        if (other == org.game.protobuf.s2c.S2CLoginMsg.Pong.getDefaultInstance()) return this;
        if (other.getServerTime() != 0) {
          setServerTime(other.getServerTime());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.game.protobuf.s2c.S2CLoginMsg.Pong parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.game.protobuf.s2c.S2CLoginMsg.Pong) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int serverTime_ ;
      /**
       * <pre>
       *服务器时间
       * </pre>
       *
       * <code>optional int32 serverTime = 1;</code>
       */
      public int getServerTime() {
        return serverTime_;
      }
      /**
       * <pre>
       *服务器时间
       * </pre>
       *
       * <code>optional int32 serverTime = 1;</code>
       */
      public Builder setServerTime(int value) {
        
        serverTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *服务器时间
       * </pre>
       *
       * <code>optional int32 serverTime = 1;</code>
       */
      public Builder clearServerTime() {
        
        serverTime_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:org.game.protobuf.s2c.Pong)
    }

    // @@protoc_insertion_point(class_scope:org.game.protobuf.s2c.Pong)
    private static final org.game.protobuf.s2c.S2CLoginMsg.Pong DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.game.protobuf.s2c.S2CLoginMsg.Pong();
    }

    public static org.game.protobuf.s2c.S2CLoginMsg.Pong getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Pong>
        PARSER = new com.google.protobuf.AbstractParser<Pong>() {
      public Pong parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Pong(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Pong> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Pong> getParserForType() {
      return PARSER;
    }

    public org.game.protobuf.s2c.S2CLoginMsg.Pong getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_game_protobuf_s2c_S2CLoginMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_game_protobuf_s2c_S2CLoginMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_game_protobuf_s2c_Pong_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_game_protobuf_s2c_Pong_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021S2CLoginMsg.proto\022\025org.game.protobuf.s" +
      "2c\"V\n\017S2CLoginMessage\022\022\n\nserverTime\030\001 \001(" +
      "\005\"/\n\005MsgID\022\031\n\025ENUN_TYPE_UNSPECIFIED\020\000\022\013\n" +
      "\006eMsgID\020\201\002\"K\n\004Pong\022\022\n\nserverTime\030\001 \001(\005\"/" +
      "\n\005MsgID\022\031\n\025ENUN_TYPE_UNSPECIFIED\020\000\022\013\n\006eM" +
      "sgID\020\312\001*;\n\nLogoutType\022\n\n\006COMMON\020\000\022\014\n\010KIC" +
      "K_OUT\020\001\022\023\n\017OTHER_PLACES_ON\020\002b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_game_protobuf_s2c_S2CLoginMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_game_protobuf_s2c_S2CLoginMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_game_protobuf_s2c_S2CLoginMessage_descriptor,
        new java.lang.String[] { "ServerTime", });
    internal_static_org_game_protobuf_s2c_Pong_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_game_protobuf_s2c_Pong_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_game_protobuf_s2c_Pong_descriptor,
        new java.lang.String[] { "ServerTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
